name: Publish to NPM  - retool components library
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    if: github.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies 🚀
        run: echo hello
    #   - name: Publish package on NPM 📦
    #     run: yarn nx publish retool-components-library
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  publish-trunk:
    if: github.ref == 'trunk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies 🚀
        run: echo hello
