name: Publish to NPM  - retool components library
on:
  push:
    branches:
      - main
    paths:
      - 'libs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies 🚀
        uses: ./.github/actions/install-dependencies
      - name: Build library 🔧
        run: yarn nx build retool-components-library
    #   - name: Publish package on NPM 📦
    #     run: yarn nx publish retool-components-library
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

